<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Mirror of the product fix in 2026_05_20_120000 — make `vendor_code`
 * unique per client instead of globally.
 *
 * Original vendors migration declared `->unique()` inline which built
 * a single global index. Two tenants couldn't share the same V-01,
 * and the wizard's per-client `nextVendorCode()` trips on it as soon
 * as a second client onboards: it picks V-02 for client B (the next
 * slot in B's sequence) and the global index rejects because client
 * A already has V-02.
 *
 * Fix: composite unique on (client_id, vendor_code). Strictly more
 * permissive than the old constraint, so existing data is safe.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('vendors', function (Blueprint $table) {
            // Default index name auto-generated by Laravel for inline
            // `->unique()` on the original migration.
            $table->dropUnique('vendors_vendor_code_unique');
            $table->unique(['client_id', 'vendor_code'], 'vendors_client_id_vendor_code_unique');
        });
    }

    public function down(): void
    {
        Schema::table('vendors', function (Blueprint $table) {
            $table->dropUnique('vendors_client_id_vendor_code_unique');
            $table->unique('vendor_code', 'vendors_vendor_code_unique');
        });
    }
};
