<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Make `product_code` unique per client instead of globally.
 *
 * The original migration declared `->string('product_code')->unique()`
 * which created a single global index. That prevents two different
 * clients from ever sharing the same human code (e.g. both clients
 * having "P-01"), and the wizard's per-client auto-code generator
 * trips on it the moment a second tenant onboards: storeCore picks
 * P-02 for client B because that's the next slot in B's sequence,
 * but the global index rejects it because client A already has P-02.
 *
 * The fix is a composite uniqueness rule that's strictly more
 * permissive: (client_id, product_code) — each client keeps its own
 * P-01, P-02, … series without colliding with anyone else's.
 *
 * If pre-existing rows somehow conflicted (same client_id + code
 * appearing twice) the new index creation would fail; in that case
 * the DBA needs to dedupe the duplicates before running this. On a
 * normal install the global-unique constraint guaranteed no dupes,
 * so the swap is safe.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('products', function (Blueprint $table) {
            // Default index name auto-generated by Laravel when the
            // original migration called `->unique()` inline.
            $table->dropUnique('products_product_code_unique');
            $table->unique(['client_id', 'product_code'], 'products_client_id_product_code_unique');
        });
    }

    public function down(): void
    {
        Schema::table('products', function (Blueprint $table) {
            $table->dropUnique('products_client_id_product_code_unique');
            $table->unique('product_code', 'products_product_code_unique');
        });
    }
};
