/**
 * Zones — the prototype's own 81, verbatim.
 *
 * Static, like the warehouses and the flags: the screen is designed before it
 * is wired. Replace what this module exports when an endpoint lands; the page
 * only ever reads ZONES.
 */

/** With racking, or an open floor / refrigerated room. */
export type ZoneType = 'rack' | 'norack';

/** How a without-rack zone stores: an open floor, or a refrigerator. */
export type ZoneStorage = '' | 'regular' | 'fridge';

/** The measured box of a regular-floor zone, and what it works out to. */
export interface ZoneDims {
  unit: 'm' | 'cm';
  length: number;
  width: number;
  height: number;
  /** How much of the volume is actually usable, as a percentage. */
  usablePct: number;
  floorArea: number;
  volume: number;
  usableVolume: number;
}

export interface Zone {
  /** ZN-001 … */
  id: string;
  /** Created on. ISO; formatted on render. */
  date: string;
  type: ZoneType;
  name: string;
  /** The warehouse this zone is inside, by its WH- code. */
  wh: string;
  /** Square feet. */
  area: number;
  /** What the zone is for — receiving, bulk storage, dispatch and so on. */
  purpose: string;
  /** Cold chain allowed, and between which temperatures. */
  cold: boolean;
  tempRange: { min: number; max: number } | null;
  /** Hazardous goods allowed. */
  haz: boolean;
  /** Only set on a without-rack zone. */
  storage: ZoneStorage;
  /** A refrigerator's capacity in litres; null unless storage is 'fridge'. */
  litres: number | null;
  /** A regular floor's measurements; null unless storage is 'regular'. */
  dims: ZoneDims | null;
  status: 'active' | 'inactive';
}

export const ZONES: Zone[] = [
  {
    id: 'ZN-001',
    date: '2025-05-08',
    type: 'rack',
    name: 'Zone P – Long Goods',
    wh: 'WH-014',
    area: 2400,
    purpose: 'Bulk Storage',
    cold: true,
    tempRange: { min: 8, max: 15 },
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'inactive',
  },
  {
    id: 'ZN-002',
    date: '2025-05-21',
    type: 'rack',
    name: 'Zone T – Overflow Racks',
    wh: 'WH-018',
    area: 2400,
    purpose: 'Dispatch / Staging',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-003',
    date: '2025-06-05',
    type: 'norack',
    name: 'Heavy Goods Floor',
    wh: 'WH-009',
    area: 6458,
    purpose: 'Bulk Storage',
    cold: false,
    tempRange: null,
    haz: false,
    storage: 'regular',
    litres: null,
    dims: { unit: 'm', length: 30, width: 20, height: 8, usablePct: 70, floorArea: 600, volume: 4800, usableVolume: 3360 },
    status: 'active',
  },
  {
    id: 'ZN-004',
    date: '2025-06-22',
    type: 'rack',
    name: 'Zone A – Fast Movers',
    wh: 'WH-001',
    area: 4500,
    purpose: 'Receiving / Inward',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-005',
    date: '2025-07-07',
    type: 'norack',
    name: 'Blood Bank Store',
    wh: 'WH-017',
    area: 800,
    purpose: 'Bulk Storage',
    cold: true,
    tempRange: { min: 8, max: 15 },
    haz: false,
    storage: 'fridge',
    litres: 10000,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-006',
    date: '2025-07-18',
    type: 'rack',
    name: 'Zone D – Spare Parts',
    wh: 'WH-004',
    area: 7500,
    purpose: 'Quarantine / QA Hold',
    cold: true,
    tempRange: { min: -40, max: -25 },
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-007',
    date: '2025-08-02',
    type: 'norack',
    name: 'Bagged Goods Area',
    wh: 'WH-014',
    area: 3789,
    purpose: 'Bulk Storage',
    cold: false,
    tempRange: null,
    haz: false,
    storage: 'regular',
    litres: null,
    dims: { unit: 'm', length: 22, width: 16, height: 6, usablePct: 70, floorArea: 352, volume: 2112, usableVolume: 1478.4 },
    status: 'active',
  },
  {
    id: 'ZN-008',
    date: '2025-08-20',
    type: 'norack',
    name: 'Frozen Food Bay',
    wh: 'WH-020',
    area: 650,
    purpose: 'Bulk Storage',
    cold: true,
    tempRange: { min: -25, max: -18 },
    haz: false,
    storage: 'fridge',
    litres: 2500,
    dims: null,
    status: 'inactive',
  },
  {
    id: 'ZN-009',
    date: '2025-09-01',
    type: 'norack',
    name: 'Chiller Bay – Dairy',
    wh: 'WH-011',
    area: 300,
    purpose: 'Pick Face / Forward Picking',
    cold: true,
    tempRange: { min: 2, max: 8 },
    haz: false,
    storage: 'fridge',
    litres: 4000,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-010',
    date: '2025-09-18',
    type: 'rack',
    name: 'Zone G – Medical Consumables',
    wh: 'WH-007',
    area: 6200,
    purpose: 'Receiving / Inward',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-011',
    date: '2025-10-02',
    type: 'rack',
    name: 'Zone J – Raw Materials',
    wh: 'WH-009',
    area: 4500,
    purpose: 'Pick Face / Forward Picking',
    cold: true,
    tempRange: { min: 2, max: 8 },
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-012',
    date: '2025-10-18',
    type: 'rack',
    name: 'Zone N – Small Parts Bins',
    wh: 'WH-013',
    area: 3200,
    purpose: 'Receiving / Inward',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-013',
    date: '2025-11-04',
    type: 'rack',
    name: 'Zone B – Slow Movers',
    wh: 'WH-002',
    area: 3200,
    purpose: 'Bulk Storage',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-014',
    date: '2025-11-16',
    type: 'norack',
    name: 'Cold Room 2 – Reagents',
    wh: 'WH-005',
    area: 800,
    purpose: 'Bulk Storage',
    cold: true,
    tempRange: { min: 2, max: 8 },
    haz: false,
    storage: 'fridge',
    litres: 7500,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-015',
    date: '2025-11-28',
    type: 'rack',
    name: 'Zone E – Packaging Materials',
    wh: 'WH-005',
    area: 2400,
    purpose: 'Returns',
    cold: false,
    tempRange: null,
    haz: true,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-016',
    date: '2025-12-19',
    type: 'norack',
    name: 'Bulk Floor – Grains',
    wh: 'WH-013',
    area: 4844,
    purpose: 'Bulk Storage',
    cold: false,
    tempRange: null,
    haz: false,
    storage: 'regular',
    litres: null,
    dims: { unit: 'm', length: 25, width: 18, height: 7, usablePct: 70, floorArea: 450, volume: 3150, usableVolume: 2205 },
    status: 'active',
  },
  {
    id: 'ZN-017',
    date: '2025-12-28',
    type: 'rack',
    name: 'Zone L – Returns Racking',
    wh: 'WH-011',
    area: 2400,
    purpose: 'Returns',
    cold: false,
    tempRange: null,
    haz: true,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-018',
    date: '2026-01-14',
    type: 'rack',
    name: 'Zone R – Export Lots',
    wh: 'WH-016',
    area: 4730,
    purpose: 'Quarantine / QA Hold',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-019',
    date: '2026-01-30',
    type: 'rack',
    name: 'Zone S – Kitting Racks',
    wh: 'WH-017',
    area: 4840,
    purpose: 'Kitting & Assembly',
    cold: false,
    tempRange: null,
    haz: true,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-020',
    date: '2026-02-16',
    type: 'norack',
    name: 'Open Yard – Pallets',
    wh: 'WH-003',
    area: 3789,
    purpose: 'Bulk Storage',
    cold: false,
    tempRange: null,
    haz: false,
    storage: 'regular',
    litres: null,
    dims: { unit: 'm', length: 22, width: 16, height: 6, usablePct: 75, floorArea: 352, volume: 2112, usableVolume: 1584 },
    status: 'active',
  },
  {
    id: 'ZN-021',
    date: '2026-03-03',
    type: 'norack',
    name: 'Quarantine Floor',
    wh: 'WH-023',
    area: 3789,
    purpose: 'Quarantine / QA Hold',
    cold: false,
    tempRange: null,
    haz: false,
    storage: 'regular',
    litres: null,
    dims: { unit: 'm', length: 22, width: 16, height: 6, usablePct: 75, floorArea: 352, volume: 2112, usableVolume: 1584 },
    status: 'inactive',
  },
  {
    id: 'ZN-022',
    date: '2026-03-13',
    type: 'rack',
    name: 'Zone C – Bulk Pallets',
    wh: 'WH-003',
    area: 3960,
    purpose: 'Pick Face / Forward Picking',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-023',
    date: '2026-03-28',
    type: 'norack',
    name: 'Chilled Pharma Store',
    wh: 'WH-023',
    area: 400,
    purpose: 'Dispatch / Staging',
    cold: true,
    tempRange: { min: 2, max: 8 },
    haz: false,
    storage: 'fridge',
    litres: 2500,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-024',
    date: '2026-04-17',
    type: 'norack',
    name: 'Pharma Fridge Bank',
    wh: 'WH-014',
    area: 800,
    purpose: 'Quarantine / QA Hold',
    cold: true,
    tempRange: { min: 2, max: 8 },
    haz: false,
    storage: 'fridge',
    litres: 2500,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-025',
    date: '2026-05-02',
    type: 'rack',
    name: 'Zone F – High Value',
    wh: 'WH-006',
    area: 2400,
    purpose: 'Dispatch / Staging',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'inactive',
  },
  {
    id: 'ZN-026',
    date: '2026-05-14',
    type: 'rack',
    name: 'Zone H – Electrical Items',
    wh: 'WH-008',
    area: 2400,
    purpose: 'Bulk Storage',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-027',
    date: '2026-06-01',
    type: 'rack',
    name: 'Zone K – Finished Goods',
    wh: 'WH-010',
    area: 6200,
    purpose: 'Quarantine / QA Hold',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-028',
    date: '2026-06-15',
    type: 'rack',
    name: 'Zone M – Mezzanine',
    wh: 'WH-012',
    area: 5940,
    purpose: 'Dispatch / Staging',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-029',
    date: '2026-07-01',
    type: 'rack',
    name: 'Zone Q – Seasonal Stock',
    wh: 'WH-015',
    area: 2400,
    purpose: 'Pick Face / Forward Picking',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-030',
    date: '2026-07-17',
    type: 'norack',
    name: 'Cross-dock Area',
    wh: 'WH-024',
    area: 3789,
    purpose: 'Dispatch / Staging',
    cold: false,
    tempRange: null,
    haz: false,
    storage: 'regular',
    litres: null,
    dims: { unit: 'm', length: 22, width: 16, height: 6, usablePct: 75, floorArea: 352, volume: 2112, usableVolume: 1584 },
    status: 'active',
  },
  {
    id: 'ZN-031',
    date: '2026-07-29',
    type: 'norack',
    name: 'Cold Room 1 – Vaccines',
    wh: 'WH-002',
    area: 400,
    purpose: 'Bulk Storage',
    cold: true,
    tempRange: { min: 2, max: 8 },
    haz: false,
    storage: 'fridge',
    litres: 2500,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-032',
    date: '2026-08-12',
    type: 'norack',
    name: 'Dock Staging Area',
    wh: 'WH-018',
    area: 3789,
    purpose: 'Dispatch / Staging',
    cold: false,
    tempRange: null,
    haz: false,
    storage: 'regular',
    litres: null,
    dims: { unit: 'm', length: 22, width: 16, height: 6, usablePct: 80, floorArea: 352, volume: 2112, usableVolume: 1689.6 },
    status: 'active',
  },
  {
    id: 'ZN-033',
    date: '2026-08-30',
    type: 'norack',
    name: 'Walk-in Freezer',
    wh: 'WH-008',
    area: 300,
    purpose: 'Bulk Storage',
    cold: true,
    tempRange: { min: -25, max: -18 },
    haz: false,
    storage: 'fridge',
    litres: 10000,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-034',
    date: '2026-09-12',
    type: 'norack',
    name: 'Floor Stack Area',
    wh: 'WH-008',
    area: 6458,
    purpose: 'Bulk Storage',
    cold: false,
    tempRange: null,
    haz: false,
    storage: 'regular',
    litres: null,
    dims: { unit: 'm', length: 30, width: 20, height: 8, usablePct: 85, floorArea: 600, volume: 4800, usableVolume: 4080 },
    status: 'active',
  },
  {
    id: 'ZN-035',
    date: '2026-09-29',
    type: 'norack',
    name: 'Drum Storage Floor',
    wh: 'WH-019',
    area: 3789,
    purpose: 'Bulk Storage',
    cold: false,
    tempRange: null,
    haz: true,
    storage: 'regular',
    litres: null,
    dims: { unit: 'm', length: 22, width: 16, height: 6, usablePct: 70, floorArea: 352, volume: 2112, usableVolume: 1478.4 },
    status: 'active',
  },
  {
    id: 'ZN-036',
    date: '2026-10-11',
    type: 'norack',
    name: 'Returns Floor',
    wh: 'WH-004',
    area: 3229,
    purpose: 'Returns',
    cold: false,
    tempRange: null,
    haz: false,
    storage: 'regular',
    litres: null,
    dims: { unit: 'm', length: 20, width: 15, height: 6, usablePct: 75, floorArea: 300, volume: 1800, usableVolume: 1350 },
    status: 'active',
  },
  {
    id: 'ZN-037',
    date: '2026-02-20',
    type: 'rack',
    name: 'Pallet Racks – Bay 1',
    wh: 'WH-001',
    area: 1800,
    purpose: 'Bulk Storage',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-038',
    date: '2026-02-24',
    type: 'rack',
    name: 'Pallet Racks – Bay 2',
    wh: 'WH-001',
    area: 2200,
    purpose: 'Pick Face / Forward Picking',
    cold: true,
    tempRange: { min: 8, max: 15 },
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-039',
    date: '2026-02-28',
    type: 'rack',
    name: 'Bin Shelving – Small Parts',
    wh: 'WH-001',
    area: 2600,
    purpose: 'Receiving / Inward',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-040',
    date: '2026-03-04',
    type: 'rack',
    name: 'Mezzanine Racks',
    wh: 'WH-002',
    area: 2200,
    purpose: 'Dispatch / Staging',
    cold: false,
    tempRange: null,
    haz: true,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-041',
    date: '2026-03-08',
    type: 'rack',
    name: 'Cantilever Racks',
    wh: 'WH-002',
    area: 2600,
    purpose: 'Kitting & Assembly',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-042',
    date: '2026-03-12',
    type: 'rack',
    name: 'Picking Racks',
    wh: 'WH-003',
    area: 2600,
    purpose: 'Returns',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-043',
    date: '2026-03-16',
    type: 'rack',
    name: 'Reserve Racks',
    wh: 'WH-003',
    area: 3000,
    purpose: 'Bulk Storage',
    cold: true,
    tempRange: { min: 2, max: 8 },
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-044',
    date: '2026-03-20',
    type: 'rack',
    name: 'Carton Flow Racks',
    wh: 'WH-003',
    area: 1300,
    purpose: 'Pick Face / Forward Picking',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-045',
    date: '2026-03-24',
    type: 'rack',
    name: 'Drive-In Racks',
    wh: 'WH-004',
    area: 3000,
    purpose: 'Receiving / Inward',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-046',
    date: '2026-03-28',
    type: 'rack',
    name: 'Pallet Racks – Bay 1',
    wh: 'WH-004',
    area: 3400,
    purpose: 'Dispatch / Staging',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-047',
    date: '2026-04-01',
    type: 'rack',
    name: 'Bin Shelving – Small Parts',
    wh: 'WH-005',
    area: 3400,
    purpose: 'Kitting & Assembly',
    cold: false,
    tempRange: null,
    haz: true,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-048',
    date: '2026-04-05',
    type: 'rack',
    name: 'Mezzanine Racks',
    wh: 'WH-005',
    area: 1500,
    purpose: 'Returns',
    cold: true,
    tempRange: { min: -25, max: -18 },
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-049',
    date: '2026-04-09',
    type: 'rack',
    name: 'Cantilever Racks',
    wh: 'WH-005',
    area: 1800,
    purpose: 'Bulk Storage',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-050',
    date: '2026-04-13',
    type: 'rack',
    name: 'High-Bay Racks',
    wh: 'WH-006',
    area: 1500,
    purpose: 'Pick Face / Forward Picking',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-051',
    date: '2026-04-17',
    type: 'rack',
    name: 'Picking Racks',
    wh: 'WH-006',
    area: 1800,
    purpose: 'Receiving / Inward',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-052',
    date: '2026-04-21',
    type: 'rack',
    name: 'Carton Flow Racks',
    wh: 'WH-007',
    area: 1800,
    purpose: 'Dispatch / Staging',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-053',
    date: '2026-04-25',
    type: 'rack',
    name: 'Drive-In Racks',
    wh: 'WH-007',
    area: 2200,
    purpose: 'Kitting & Assembly',
    cold: true,
    tempRange: { min: 8, max: 15 },
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-054',
    date: '2026-04-29',
    type: 'rack',
    name: 'Pallet Racks – Bay 1',
    wh: 'WH-007',
    area: 2600,
    purpose: 'Returns',
    cold: false,
    tempRange: null,
    haz: true,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-055',
    date: '2026-05-03',
    type: 'rack',
    name: 'Pallet Racks – Bay 2',
    wh: 'WH-008',
    area: 2200,
    purpose: 'Bulk Storage',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-056',
    date: '2026-05-07',
    type: 'rack',
    name: 'Bin Shelving – Small Parts',
    wh: 'WH-008',
    area: 2600,
    purpose: 'Pick Face / Forward Picking',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-057',
    date: '2026-05-11',
    type: 'rack',
    name: 'Cantilever Racks',
    wh: 'WH-009',
    area: 2600,
    purpose: 'Receiving / Inward',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-058',
    date: '2026-05-15',
    type: 'rack',
    name: 'High-Bay Racks',
    wh: 'WH-009',
    area: 3000,
    purpose: 'Dispatch / Staging',
    cold: true,
    tempRange: { min: 2, max: 8 },
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-059',
    date: '2026-05-19',
    type: 'rack',
    name: 'Picking Racks',
    wh: 'WH-009',
    area: 3400,
    purpose: 'Kitting & Assembly',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-060',
    date: '2026-05-23',
    type: 'rack',
    name: 'Reserve Racks',
    wh: 'WH-010',
    area: 3000,
    purpose: 'Returns',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-061',
    date: '2026-05-27',
    type: 'rack',
    name: 'Carton Flow Racks',
    wh: 'WH-010',
    area: 3400,
    purpose: 'Bulk Storage',
    cold: false,
    tempRange: null,
    haz: true,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-062',
    date: '2026-05-31',
    type: 'rack',
    name: 'Pallet Racks – Bay 1',
    wh: 'WH-011',
    area: 3400,
    purpose: 'Pick Face / Forward Picking',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-063',
    date: '2026-06-04',
    type: 'rack',
    name: 'Pallet Racks – Bay 2',
    wh: 'WH-011',
    area: 1500,
    purpose: 'Receiving / Inward',
    cold: true,
    tempRange: { min: -25, max: -18 },
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-064',
    date: '2026-06-08',
    type: 'rack',
    name: 'Bin Shelving – Small Parts',
    wh: 'WH-011',
    area: 1800,
    purpose: 'Dispatch / Staging',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-065',
    date: '2026-06-12',
    type: 'rack',
    name: 'Mezzanine Racks',
    wh: 'WH-012',
    area: 1500,
    purpose: 'Kitting & Assembly',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-066',
    date: '2026-06-16',
    type: 'rack',
    name: 'Cantilever Racks',
    wh: 'WH-012',
    area: 1800,
    purpose: 'Returns',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-067',
    date: '2026-06-20',
    type: 'rack',
    name: 'Picking Racks',
    wh: 'WH-013',
    area: 1800,
    purpose: 'Bulk Storage',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-068',
    date: '2026-06-24',
    type: 'rack',
    name: 'Reserve Racks',
    wh: 'WH-013',
    area: 2200,
    purpose: 'Pick Face / Forward Picking',
    cold: true,
    tempRange: { min: 8, max: 15 },
    haz: true,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-069',
    date: '2026-06-28',
    type: 'rack',
    name: 'Carton Flow Racks',
    wh: 'WH-013',
    area: 2600,
    purpose: 'Receiving / Inward',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-070',
    date: '2026-07-02',
    type: 'rack',
    name: 'Drive-In Racks',
    wh: 'WH-014',
    area: 2200,
    purpose: 'Dispatch / Staging',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-071',
    date: '2026-07-06',
    type: 'rack',
    name: 'Pallet Racks – Bay 1',
    wh: 'WH-014',
    area: 2600,
    purpose: 'Kitting & Assembly',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-072',
    date: '2026-07-10',
    type: 'rack',
    name: 'Bin Shelving – Small Parts',
    wh: 'WH-015',
    area: 2600,
    purpose: 'Returns',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-073',
    date: '2026-07-14',
    type: 'rack',
    name: 'Mezzanine Racks',
    wh: 'WH-015',
    area: 3000,
    purpose: 'Bulk Storage',
    cold: true,
    tempRange: { min: 2, max: 8 },
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-074',
    date: '2026-07-18',
    type: 'rack',
    name: 'Cantilever Racks',
    wh: 'WH-015',
    area: 3400,
    purpose: 'Pick Face / Forward Picking',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-075',
    date: '2026-07-22',
    type: 'rack',
    name: 'High-Bay Racks',
    wh: 'WH-016',
    area: 3000,
    purpose: 'Receiving / Inward',
    cold: false,
    tempRange: null,
    haz: true,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-076',
    date: '2026-07-26',
    type: 'rack',
    name: 'Picking Racks',
    wh: 'WH-016',
    area: 3400,
    purpose: 'Dispatch / Staging',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-077',
    date: '2026-07-30',
    type: 'rack',
    name: 'Carton Flow Racks',
    wh: 'WH-017',
    area: 3400,
    purpose: 'Kitting & Assembly',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-078',
    date: '2026-08-03',
    type: 'rack',
    name: 'Drive-In Racks',
    wh: 'WH-017',
    area: 1500,
    purpose: 'Returns',
    cold: true,
    tempRange: { min: -25, max: -18 },
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-079',
    date: '2026-08-07',
    type: 'rack',
    name: 'Pallet Racks – Bay 1',
    wh: 'WH-017',
    area: 1800,
    purpose: 'Bulk Storage',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-080',
    date: '2026-08-11',
    type: 'rack',
    name: 'Pallet Racks – Bay 2',
    wh: 'WH-018',
    area: 1500,
    purpose: 'Pick Face / Forward Picking',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
  {
    id: 'ZN-081',
    date: '2026-08-15',
    type: 'rack',
    name: 'Bin Shelving – Small Parts',
    wh: 'WH-018',
    area: 1800,
    purpose: 'Receiving / Inward',
    cold: false,
    tempRange: null,
    haz: false,
    storage: '',
    litres: null,
    dims: null,
    status: 'active',
  },
];
